#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

function arg(name, fallback = null) {
  const i = process.argv.indexOf(name);
  return i >= 0 && i + 1 < process.argv.length ? process.argv[i + 1] : fallback;
}

function parseCsv(text) {
  const rows = [];
  const lines = text.split(/\r?\n/).filter(Boolean);
  if (!lines.length) return rows;
  const headers = splitCsv(lines[0]);
  for (const line of lines.slice(1)) {
    const cols = splitCsv(line);
    const row = {};
    headers.forEach((h, i) => row[h] = cols[i] || "");
    rows.push(row);
  }
  return rows;
}

function splitCsv(line) {
  const out = [];
  let cur = "";
  let q = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"' && line[i + 1] === '"') { cur += '"'; i++; continue; }
    if (ch === '"') { q = !q; continue; }
    if (ch === "," && !q) { out.push(cur); cur = ""; continue; }
    cur += ch;
  }
  out.push(cur);
  return out;
}

function csvQuote(v) {
  const s = String(v ?? "");
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function exprFor(row) {
  const family = row.family || row.expr || "Hyd";
  if (row.expr && row.expr !== "Mixed") return row.expr;
  const map = {
    HBD: "Don",
    HBA: "Acc",
    Hyd: "Hyd",
    Aro: "Aro",
    Pos: "Cat",
    Neg: "Ani",
    Metal: "Met",
    ExcludedVolume: "XVol",
    Mixed: "Don$mAcc"
  };
  return map[family] || "Hyd";
}

function writePh4(rows, out) {
  const lines = [];
  lines.push("#moe:ph4que 2024.06");
  lines.push("#pharmacophore generated by moe-ph4-cli");
  lines.push(`#feature ${rows.length} expr tt color ix x r y r z r r r ebits ix gbits ix`);
  for (const row of rows) {
    const expr = exprFor(row);
    const x = Number(row.x).toFixed(3);
    const y = Number(row.y).toFixed(3);
    const z = Number(row.z).toFixed(3);
    const r = Number(row.radius || row.r || 1.4).toFixed(3);
    lines.push(`${expr} 16777215 ${x} ${y} ${z} ${r} 0 0`);
  }
  fs.writeFileSync(out, lines.join("\n") + "\n", "utf8");
}

function writeSvl(rows, outPh4, outSvl) {
  const outPath = outPh4.replace(/\\/g, "/");
  const lines = [];
  lines.push("function ph4_QueryCreate;");
  lines.push("function ph4_QueryCreateF;");
  lines.push("function ph4_QueryWriteFile;");
  lines.push("local q;");
  lines.push("q = ph4_QueryCreate [];");
  for (const row of rows) {
    const expr = exprFor(row).replace(/'/g, "");
    const x = Number(row.x).toFixed(4);
    const y = Number(row.y).toFixed(4);
    const z = Number(row.z).toFixed(4);
    const r = Number(row.radius || row.r || 1.4).toFixed(4);
    lines.push(`ph4_QueryCreateF [q, [[pos:[${x}, ${y}, ${z}], rad:${r}, expr:'${expr}']], 0];`);
  }
  lines.push(`ph4_QueryWriteFile [q, '${outPath}'];`);
  fs.writeFileSync(outSvl, lines.join("\n") + "\n", "utf8");
}

function main() {
  const csv = arg("--csv");
  const out = arg("--out");
  const svl = arg("--svl");
  if (!csv || !out) {
    console.error("Usage: node write_selected_ph4.js --csv curated_features.csv --out curated_model.ph4 [--svl write_selected_ph4.svl]");
    process.exit(2);
  }
  const rows = parseCsv(fs.readFileSync(csv, "utf8"));
  fs.mkdirSync(path.dirname(out), { recursive: true });
  writePh4(rows, out);
  if (svl) writeSvl(rows, out, svl);
}

main();
