#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const cp = require("child_process");

function usage() {
  console.log(`Usage:
  node moe_native_site_ph4.js --config moe_native_config.json [--run]

Config fields:
  structure_pdb        required, input PDB path
  output_dir           required, run output directory
  moe_bin              optional, path to moebatch.exe
  receptor_chain       optional, receptor chain id used in comments and display labels
  ligand_chain         optional, ligand/peptide chain id used in comments and display labels
  site_radius          optional, default 6.0 Angstrom
  feature_perspective  optional, ligand | receptor | complement, default ligand

The script emits a MOE SVL driver plus a normalized manifest. Use --run to call moebatch.
`);
}

function parseArgs(argv) {
  const args = {};
  for (let i = 2; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === "--run") args.run = true;
    else if (a.startsWith("--")) {
      const key = a.slice(2).replace(/-/g, "_");
      const val = argv[i + 1];
      if (!val || val.startsWith("--")) throw new Error(`Missing value for ${a}`);
      args[key] = val;
      i += 1;
    } else {
      throw new Error(`Unknown argument: ${a}`);
    }
  }
  return args;
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8").replace(/^\uFEFF/, ""));
}

function winToSvl(file) {
  return path.resolve(file).replace(/\\/g, "/").replace(/'/g, "\\'");
}

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function nowIso() {
  return new Date().toISOString();
}

function writeSvl(cfg, paths) {
  const pdb = winToSvl(cfg.structure_pdb);
  const rawPh4 = winToSvl(paths.rawPh4);
  const rawCsv = winToSvl(paths.rawCsv);
  const displaySvl = winToSvl(paths.displaySvl);
  const radius = Number(cfg.site_radius || 6.0);
  const perspective = cfg.feature_perspective || "ligand";
  const receptorChain = cfg.receptor_chain || "";
  const ligandChain = cfg.ligand_chain || "";

  const svl = `#set title 'MOE Native Site Pharmacophore Driver'
#set class 'SVL:run'
// MOE native site pharmacophore driver generated by moe_native_site_ph4.js
// This driver intentionally keeps the MOE calls explicit so another agent can inspect logs.

function ReadPDB;
function ph4_AnnotationRec;
function ph4_AnnotationPairs;
function ph4_QueryOpen;
function ph4_QueryCreateF;
function ph4_QueryWriteFile;
function ph4_QueryClose;

global function main []

	local pdb_file = '${pdb}';
	local out_ph4 = '${rawPh4}';
	local out_csv = '${rawCsv}';
	local out_display = '${displaySvl}';
	local site_radius = ${radius.toFixed(3)};
	local feature_perspective = '${perspective}';
	local receptor_chain = '${receptorChain}';
	local ligand_chain = '${ligandChain}';

	write 'MOE native pharmacophore driver\\n';
	write 'PDB, perspective, and chain hints are recorded in moe_native_manifest.json\\n';

	ReadPDB [pdb_file, []];

// Agent note:
// 1. Use MOE atom selectors or manually promoted selections when chain hints are insufficient.
// 2. ph4_AnnotationRec should be run with rec:1; otherwise ph4_AnnotationPairs may exit NYET.
// 3. Keep ligand-query perspective for article-style peptide/ligand features.
// 4. Save raw annotations before mechanism compression.

// The following block is deliberately conservative because MOE point-release SVL signatures vary.
// If your MOE build supports direct atom-vector selections, replace rec_atoms/site_atoms below
// with the appropriate vectors and uncomment the AnnotationPairs call.
//
// local rec_atoms = atoms[];       // TODO: receptor atom vector
// local site_atoms = atoms[];      // TODO: ligand/peptide or pocket atom vector
// local rec_ann = ph4_AnnotationRec [rec_atoms, [rec:1, _sol:0]];
// local pair_ann = ph4_AnnotationPairs [rec_atoms, site_atoms, [rec:1, _sol:0]];
// print [pair_ann, '\\n'];

	local fh = fopenw out_csv;
	fwrite [fh, 'id,family,x,y,z,radius,source,perspective,notes\\n'];
	fclose fh;

	local q = ph4_QueryOpen [];
	ph4_QueryWriteFile [q, out_ph4];
	ph4_QueryClose q;

	local dh = fopenw out_display;
	fwrite [dh, '// Display helper generated with the same coordinate frame.\\n'];
	fwrite [dh, '// Load structure, then load raw/curated .ph4 query in MOE.\\n'];
	fclose dh;

	write 'Wrote placeholder raw pharmacophore files\\n';

endfunction
`;
  fs.writeFileSync(paths.driverSvl, svl, "utf8");
}

function main() {
  const args = parseArgs(process.argv);
  if (!args.config) {
    usage();
    process.exit(2);
  }
  const cfg = readJson(args.config);
  if (!cfg.structure_pdb || !cfg.output_dir) {
    throw new Error("Config requires structure_pdb and output_dir");
  }

  const outDir = path.resolve(cfg.output_dir);
  const rawDir = path.join(outDir, "02_moe_raw");
  ensureDir(rawDir);
  const paths = {
    driverSvl: path.join(rawDir, "moe_native_site_ph4.svl"),
    rawPh4: path.join(rawDir, "moe_raw_site_query.ph4"),
    rawCsv: path.join(rawDir, "moe_raw_features.csv"),
    displaySvl: path.join(rawDir, "display_structure_and_raw_ph4.svl"),
    log: path.join(rawDir, "moe_native_site_ph4.log"),
    manifest: path.join(rawDir, "moe_native_manifest.json")
  };

  writeSvl(cfg, paths);
  const manifest = {
    created_at: nowIso(),
    config: cfg,
    paths,
    execution: {
      ran_moebatch: Boolean(args.run),
      moe_bin: cfg.moe_bin || "C:/Program Files/moe2024/bin-win64/moebatch.exe"
    },
    notes: [
      "This is the MOE-native raw annotation layer. Mechanism compression must be done after raw features are emitted.",
      "Article-style models usually use ligand/peptide-side feature perspective unless the paper explicitly says receptor-complement features."
    ]
  };

  if (args.run) {
    const moeBin = cfg.moe_bin || "C:\\Program Files\\moe2024\\bin-win64\\moebatch.exe";
    const result = cp.spawnSync(moeBin, ["-run", paths.driverSvl], {
      cwd: rawDir,
      encoding: "utf8",
      windowsHide: true
    });
    fs.writeFileSync(paths.log, [
      `command=${moeBin} -run ${paths.driverSvl}`,
      `status=${result.status}`,
      `error=${result.error ? result.error.message : ""}`,
      "",
      "STDOUT",
      result.stdout || "",
      "",
      "STDERR",
      result.stderr || ""
    ].join("\n"), "utf8");
    manifest.execution.status = result.status;
    manifest.execution.error = result.error ? result.error.message : "";
    if (result.status !== 0) {
      manifest.execution.warning = "moebatch returned non-zero status; inspect the log and references/svl_errors.md.";
    }
  }

  fs.writeFileSync(paths.manifest, JSON.stringify(manifest, null, 2), "utf8");
  console.log(`Wrote ${paths.driverSvl}`);
  console.log(`Wrote ${paths.manifest}`);
  if (args.run) console.log(`Wrote ${paths.log}`);
}

main();
